#Converting fasta to csv format

In [ ]:
!pip3 install fastatocsv

In [ ]:
import fasta2csv.converter
fasta2csv.converter.convert("algaeTest.fas","new_algaeTest.csv")
fasta2csv.converter.convert("algaeTrain.fas","new_algaeTrain.csv")
fasta2csv.converter.convert("batsTrain.fas","new_batsTrain.csv")
fasta2csv.converter.convert("batsTest.fas","new_batsTest.csv")
fasta2csv.converter.convert("fishesTrain.fas","new_fishesTrain.csv")
fasta2csv.converter.convert("fishesTest.fas","new_fishesTest.csv")
fasta2csv.converter.convert("fungiTrain.fas","new_fungiTrain.csv")
fasta2csv.converter.convert("fungiTest.fas","new_fungiTest.csv")
fasta2csv.converter.convert("CypraeidaeTrain.fasta","new_cypTrain.csv")
fasta2csv.converter.convert("CypraeidaeTest.fasta","new_cypTest.csv")

'new_cypTest.csv'

## Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import re
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [ ]:
# %tensorflow_version 2.x
physical_devices = tf.config.list_physical_devices('GPU')

print("GPU:", tf.config.list_physical_devices('GPU'))
print("Num GPUs:", len(physical_devices))

GPU: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Num GPUs: 1


#Reading and Cleaning the dataset

###Algae

In [ ]:
data_algaetrain = pd.read_csv('new_algaeTrain.csv')
X_algtrain = data_algaetrain.iloc[:, :-1].values
Y_algtrain = data_algaetrain.iloc[:, -1].values

data_algaetest = pd.read_csv('new_algaeTest.csv')
X_algtest = data_algaetest.iloc[:, :-1].values
Y_algtest = data_algaetest.iloc[:, -1].values

In [ ]:
data_algaetrain.head()

Properties  \
0  GBVN2896-11|Chlorogonium capillatum|rbcL|AB010235   
1  GBVN2897-11|Chlorogonium capillatum|rbcL|AB010234   
2  GBVN2898-11|Chlorogonium capillatum|rbcL|AB010233   
3  GBVN2899-11|Chlorogonium capillatum|rbcL|AB010232   
4  GBVN2900-11|Chlorogonium capillatum|rbcL|AB010231   

                                            Sequence  
0  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...  
1  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...  
2  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...  
3  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...  
4  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...

In [ ]:
#Extracting only the species name
X_algtrainnew=[]
for i in X_algtrain:
  s=str(i)
  x_algtrain= s.split('|')[1]
  X_algtrainnew.append(x_algtrain)

X_algtestnew=[]
for i in X_algtest:
  s=str(i)
  x_algtest= s.split('|')[1]
  X_algtestnew.append(x_algtest)

Y_algtrainnew=[]
for dna in Y_algtrain:
  dna = re.sub('[^ATCG]', '', dna)
  Y_algtrainnew.append(dna)

Y_algtestnew=[]
for dna in Y_algtest:
  dna = re.sub('[^ATCG]', '', dna)
  Y_algtestnew.append(dna)

In [ ]:
new_algtraindf= pd.DataFrame(list(zip(X_algtrainnew, Y_algtrainnew)),columns =['Properties', 'Sequence'])
new_algtraindf.head(5)

Properties                                           Sequence
0  Chlorogonium capillatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...
1  Chlorogonium capillatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...
2  Chlorogonium capillatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...
3  Chlorogonium capillatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...
4  Chlorogonium capillatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...

In [ ]:
new_algtestdf= pd.DataFrame(list(zip(X_algtestnew, Y_algtestnew)),columns =['Properties', 'Sequence'])
new_algtestdf.head(5)

Properties                                           Sequence
0  Chlorogonium capillatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...
1  Chlorogonium capillatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...
2   Chlorogonium complexum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTACTACA...
3   Chlorogonium elongatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...
4   Chlorogonium elongatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACATACTACA...

In [ ]:
new_algtraindf['Properties'].nunique()

5

In [ ]:
new_algtestdf['Properties'].nunique()

5

###Bats

In [ ]:
data_batstrain = pd.read_csv('new_batsTrain.csv')
X_batstrain = data_batstrain.iloc[:, :-1].values
Y_batstrain = data_batstrain.iloc[:, -1].values

data_batstest = pd.read_csv('new_batsTest.csv')
X_batstest = data_batstest.iloc[:, :-1].values
Y_batstest = data_batstest.iloc[:, -1].values

In [ ]:
#Extracting only the species name
X_batstrainnew=[]
for i in X_batstrain:
  s=str(i)
  x_batstrain= s.split('|')[1]
  X_batstrainnew.append(x_batstrain)

X_batstestnew=[]
for i in X_batstest:
  s=str(i)
  x_batstest= s.split('|')[1]
  X_batstestnew.append(x_batstest)

Y_batstrainnew=[]
for dna in Y_batstrain:
  dna = re.sub('[^ATCG]', '', dna)
  Y_batstrainnew.append(dna)

Y_batstestnew=[]
for dna in Y_batstest:
  dna = re.sub('[^ATCG]', '', dna)
  Y_batstestnew.append(dna)

In [ ]:
new_batstraindf= pd.DataFrame(list(zip(X_batstrainnew, Y_batstrainnew)),columns =['Properties', 'Sequence'])
new_batstraindf.head(5)

Properties                                           Sequence
0  Ametrida centurio  ACATTGTACTTACTATTTGGTGCTTGAGCAGGAATAGTAGGTACCG...
1  Ametrida centurio  ACATTGTACTTACTATTTGGTGCTTGAGCAGGAATAGTAGGTACCG...
2  Ametrida centurio  ACATTGTACTTACTATTTGGTGCTTGAGCAGGAATAGTAGGTACCG...
3  Ametrida centurio  ACATTGTACTTACTATTTGGTGCTTGAGCAGGAATAGTAGGTACCG...
4  Ametrida centurio  ACATTGTACTTACTATTTGGCGCTTGAGCAGGAATAGTAGGTACCG...

In [ ]:
new_batstestdf= pd.DataFrame(list(zip(X_batstestnew, Y_batstestnew)),columns =['Properties', 'Sequence'])
new_batstestdf.head(5)

Properties                                           Sequence
0  Ametrida centurio  ACATTGTACTTACTATTTGGCGCTTGAGCAGGGATAGTAGGTACCG...
1    Anoura caudifer  ACTCTGTACTTACTATTCGGCGCCTGAGCTGGCATAGTAGGTACCG...
2    Anoura caudifer  ACTCTGTACTTACTATTCGGCGCCTGAGCTGGCATAGTAGGTACCG...
3   Anoura geoffroyi  ACTCTATACTTACTGTTTGGTGCCTGAGCCGGTATAGTAGGCACTG...
4   Anoura geoffroyi  ACTCTATACTTACTGTTTGGTGCCTGAGCCGGTATAGTAGGCACTG...

In [ ]:
new_batstraindf['Properties'].nunique()

94

In [ ]:
new_batstestdf['Properties'].nunique()

56

###Fishes

In [ ]:
data_fishestrain = pd.read_csv('new_fishesTrain.csv')
X_fishestrain = data_fishestrain['Properties']
Y_fishestrain = data_fishestrain.iloc[:,-1].values

data_fishestest = pd.read_csv('new_fishesTest.csv')
X_fishestest = data_fishestest['Properties']
Y_fishestest = data_fishestest.iloc[:,-1].values

In [ ]:
#Extracting only the species name
X_fishestrainnew=[]
for i in X_fishestrain:
  s=str(i)
  x_fishestrain= s.split('|')[1]
  X_fishestrainnew.append(x_fishestrain)

X_fishestestnew=[]
for i in X_fishestest:
  s=str(i)
  x_fishestest= s.split('|')[1]
  X_fishestestnew.append(x_fishestest)

Y_fishestrainnew=[]
for dna in Y_fishestrain:
  dna = re.sub('[^ATCG]', '', dna)
  Y_fishestrainnew.append(dna)

Y_fishestestnew=[]
for dna in Y_fishestest:
  dna = re.sub('[^ATCG]', '', dna)
  Y_fishestestnew.append(dna)

In [ ]:
new_fishestraindf= pd.DataFrame(list(zip(X_fishestrainnew, Y_fishestrainnew)),columns =['Properties', 'Sequence'])
new_fishestraindf.head(5)

Properties                                           Sequence
0  Ompok bimaculatus   CCTTTACCTAGTATTTGGTGCCTGAGCCGGAATAGTTGGTACAGCC...
1  Ompok bimaculatus   CCTTTACCTAGTATTTGGTGCCTGAGCCGGAATAGTTGGTACAGCC...
2  Ompok bimaculatus   CCTTTACCTAGTATTTGGTGCCTGAGCCGGAATAGTTGGTACAGCC...
3  Ompok bimaculatus   CCTTTACCTAGTATTTGGTGCCTGAGCCGGAATAGTTGGTACAGCC...
4  Ompok bimaculatus   CCTTTACCTAGTATTTGGTGCCTGAGCCGGAATAGTTGGTACAGCC...

In [ ]:
new_fishestestdf= pd.DataFrame(list(zip(X_fishestestnew, Y_fishestestnew)),columns =['Properties', 'Sequence'])
new_fishestestdf.head(5)

Properties                                           Sequence
0  Ompok bimaculatus   CCTTTACCTAGTATTTGGTGCCTGAGCCGGAATAGTTGGTACAGCC...
1  Ompok bimaculatus   CCTTTACCTAGTATTTGGTGCCTGAGCCGGAATAGTTGGTACAGCC...
2  Ompok bimaculatus   CCTTTACCTAGTATTTGGTGCCTGAGCCGGAATAGTTGGTACAGCC...
3  Ompok bimaculatus   CCTTTACCTAGTATTTGGTGCCTGAGCCGGAATAGTTGGTACAGCC...
4  Ompok bimaculatus   CCTTTACCTAGTATTTGGTGCCTGAGCCGGAATAGTTGGTACAGCC...

In [ ]:
new_fishestraindf['Properties'].nunique()

82

In [ ]:
new_fishestestdf['Properties'].nunique()

52

###Fungi

In [ ]:
data_fungitrain = pd.read_csv('new_fungiTrain.csv')
X_fungitrain = data_fungitrain['Properties']
Y_fungitrain = data_fungitrain.iloc[:,-1].values

data_fungitest = pd.read_csv('new_fungiTest.csv')
X_fungitest = data_fungitest['Properties']
Y_fungitest = data_fungitest.iloc[:,-1].values

In [ ]:
#Extracting only the species name
X_fungitrainnew=[]
for i in X_fungitrain:
  s=str(i)
  x_fungitrain= s.split('|')[1]
  X_fungitrainnew.append(x_fungitrain)

X_fungitestnew=[]
for i in X_fungitest:
  s=str(i)
  x_fungitest= s.split('|')[1]
  X_fungitestnew.append(x_fungitest)

Y_fungitrainnew=[]
for dna in Y_fungitrain:
  dna = re.sub('[^ATCG]', '', dna)
  Y_fungitrainnew.append(dna)

Y_fungitestnew=[]
for dna in Y_fungitest:
  dna = re.sub('[^ATCG]', '', dna)
  Y_fungitestnew.append(dna)

In [ ]:
new_fungitraindf= pd.DataFrame(list(zip(X_fungitrainnew, Y_fungitrainnew)),columns =['Properties', 'Sequence'])
new_fungitraindf.head(5)

Properties  \
0  Melampsora medusaetremuloidea   
1  Melampsora medusaetremuloidea   
2  Melampsora medusaetremuloidea   
3  Melampsora medusaetremuloidea   
4  Melampsora medusaetremuloidea   

                                            Sequence  
0  CATTAATACATGTTGAGTTGCTTAAATGCGATTCTTTGTATACTAT...  
1  CATTAATACATGTTGAGTTGCTTAAATGCGATTCTTTGTATACTAT...  
2  GAAAAACAGCATCATTGAAGGTGAAAATCCTGTAAATGATATGGAC...  
3  CATTAATACATGTTGAGTTGCTTAAATGCGATTCTTTGTATACTAT...  
4  CATTAATACATGTTGAGTTGCTTAAATGCGATTCTTTGTATACTAT...

In [ ]:
new_fungitestdf= pd.DataFrame(list(zip(X_fungitestnew, Y_fungitestnew)),columns =['Properties', 'Sequence'])
new_fungitestdf.head(5)

Properties  \
0  Melampsora medusaetremuloidea   
1  Melampsora medusaetremuloidea   
2         Melampsora aecidioides   
3         Melampsora aecidioides   
4  Melampsora abietiscanadiensis   

                                            Sequence  
0  CATTAATACATGTTGAGTTGCTTAAATGCGATTCTTTGTATACTAT...  
1  GAAAAACAGCATCATTGAAGGTGAAAATCCTGTAAATGATATGGAC...  
2  CATTAATACATGTTGAGCGCACTTTAATGTGACTCTTTGTATCAAC...  
3  CATTAATACATGTTGAGCGCACTTTAATGTGACTCTTTGTATCAAC...  
4  CATTAATACATGTTGAGTTGCTTCAATGCGATTCTTTGTATATCAT...

In [ ]:
new_fungitraindf['Properties'].nunique()

8

In [ ]:
new_fungitestdf['Properties'].nunique()

7

###Cypraeidae

In [ ]:
data_cyptrain = pd.read_csv('new_cypTrain.csv')
X_cyptrain = data_cyptrain['Properties']
Y_cyptrain = data_cyptrain.iloc[:,-1].values

data_cyptest = pd.read_csv('new_cypTest.csv')
X_cyptest = data_cyptest['Properties']
Y_cyptest = data_cyptest.iloc[:,-1].values

In [ ]:
#Extracting only the species name
X_cyptrainnew=[]
for i in X_cyptrain:
  s=str(i)
  x_cyptrain= s.split('|')[1]
  X_cyptrainnew.append(x_cyptrain)

X_cyptestnew=[]
for i in X_cyptest:
  s=str(i)
  x_cyptest= s.split('|')[1]
  X_cyptestnew.append(x_cyptest)

Y_cyptrainnew=[]
for dna in Y_cyptrain:
  dna = re.sub('[^ATCG]', '', dna)
  Y_cyptrainnew.append(dna)

Y_cyptestnew=[]
for dna in Y_cyptest:
  dna = re.sub('[^ATCG]', '', dna)
  Y_cyptestnew.append(dna)

In [ ]:
new_cyptraindf= pd.DataFrame(list(zip(X_cyptrainnew, Y_cyptrainnew)),columns =['Properties', 'Sequence'])
new_cyptraindf.head(5)

Properties                                           Sequence
0    Annepona_mariae  GGCATATGATCAGGTTTAGTTGGAACGGCCCTTAGTTTATTGATTC...
1    Annepona_mariae  TTAGTTGGAACGGCCCTTAGTTTATTGATTCGAGCAGAGTTAGGTC...
2    Annepona_mariae  TTAGTTGGAACGGCCCTTAGTTTATTGATTCGAGCAGAGTTAGGTC...
3    Annepona_mariae  GGCATATGATCAGGTCTAGTTGGAACGGCCCTTAGTTTATTGATTC...
4  Arestorides_argus  GGTATGTGGTCAGGCCTGGTTGGAACAGCTTTAAGTCTATTAATTC...

In [ ]:
new_cyptestdf= pd.DataFrame(list(zip(X_cyptestnew, Y_cyptestnew)),columns =['Properties', 'Sequence'])
new_cyptestdf.head(5)

Properties                                           Sequence
0    Annepona_mariae  GGCATATGATCAGGTTTAGTTGGAACGGCCCTTAGTTTATTGATTC...
1   Bistolia_hirundo  GGTATATGATCAGGTTTAGTCGGGACAGCTCTTAGTTTACTAATTC...
2   Bistolia_hirundo  GGTATATGGTCAGGTTTAGTCGGGACAGCTCTTAGTTTACTAATTC...
3   Bistolia_hirundo  GGTATATGATCAGGTTTAGTCGGGACAGCTCTTAGTTTACTAATTC...
4  Bistolida_kieneri  GGTATATGATCAGGTTTAGTTGGAACAGCTCTTAGTTTATTAATTC...

In [ ]:
new_cyptraindf['Properties'].nunique()

211

In [ ]:
new_cyptestdf['Properties'].nunique()

111

###Concatenation of Datadset

In [ ]:
finaltrain_dataset = pd.concat([new_algtraindf, new_batstraindf,new_fishestraindf , new_fungitraindf, new_cyptraindf])
finaltrain_dataset.to_csv('finaltrain_data.csv', index=False)

In [ ]:
finaltest_dataset = pd.concat([new_algtestdf, new_batstestdf,new_fishestestdf , new_fungitestdf, new_cyptestdf])
finaltest_dataset.to_csv('finaltest_data.csv', index=False)

In [ ]:
finaltrain_dataset.head(5)

Properties                                           Sequence
0  Chlorogonium capillatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...
1  Chlorogonium capillatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...
2  Chlorogonium capillatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...
3  Chlorogonium capillatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...
4  Chlorogonium capillatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...

In [ ]:
finaltest_dataset.head(5)

Properties                                           Sequence
0  Chlorogonium capillatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...
1  Chlorogonium capillatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...
2   Chlorogonium complexum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTACTACA...
3   Chlorogonium elongatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACTTATTACA...
4   Chlorogonium elongatum  GCTGGCTTCAAAGCAGGTGTAAAAGATTACCGTTTAACATACTACA...

##Data Processing

In [ ]:
datatrain = pd.read_csv('finaltrain_data.csv')
labeltrain = datatrain.iloc[:, 0].values
sequencestrain = datatrain.iloc[:, -1].values

In [ ]:
datatest = pd.read_csv('finaltest_data.csv')
labeltest = datatest.iloc[:, 0].values
sequencestest = datatest.iloc[:, -1].values

###Convert DNA sequences to numerical representations





In [ ]:
# Here, a simple encoding is used where A=1, C=2, G=3, T=4
def encode_sequence(sequence):
    encoding = {'A': 1, 'C': 2, 'G': 3, 'T': 4}
    return [encoding[base] for base in sequence]

encoded_sequencestrain = [encode_sequence(seq) for seq in sequencestrain]
encoded_sequencestest = [encode_sequence(seq) for seq in sequencestest]

## Convert labels to numerical labels using LabelEncoder


In [ ]:
label_encoder = LabelEncoder()
label_encoder.fit(labeltrain)
encoded_labelstrain = label_encoder.transform(labeltrain)
encoded_labelstest = label_encoder.transform(labeltest)

In [ ]:
np.save('label_encoder.npy', label_encoder.classes_)

# Pad sequences to a common length (assuming you're using variable-length sequences)

In [ ]:
max_sequence_length = max(len(seq) for seq in encoded_sequencestrain)
X_train_padded = tf.keras.preprocessing.sequence.pad_sequences(encoded_sequencestrain, maxlen=max_sequence_length, padding='post')
X_test_padded = tf.keras.preprocessing.sequence.pad_sequences(encoded_sequencestest, maxlen=max_sequence_length, padding='post')

In [ ]:
print(max_sequence_length)

1128


In [ ]:
print(X_train_padded)

[[3 2 4 ... 2 1 2]
 [3 2 4 ... 2 1 2]
 [3 2 4 ... 2 1 2]
 ...
 [3 3 4 ... 0 0 0]
 [3 3 4 ... 0 0 0]
 [3 3 4 ... 0 0 0]]


#Training the Models on dataset

## Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier =  LogisticRegression(random_state=0)
classifier.fit(X_train_padded,encoded_labelstrain)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

### Predicting the Test set results

In [ ]:
y_pred= classifier.predict(X_test_padded)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
print('Accuracy of Logistic Regression is: {0}%'.format(accuracy_score(encoded_labelstest, y_pred)*100))

Accuracy of Logistic Regression is: 90.59011164274322%


In [ ]:
str="ACCCTATATCTCCTATTCGGTGCTTGAGCCGGGATAGTTGGGACCGCTTTGAGTCTTCTTATCCGAGCCGAATTAGGACAACCAGGAGCCCTTTTGGGAGACGACCAAATCTACAATGTAATCGTAACTGCTCATGCCTTTGTAATAATTTTTTTCATAGTAATGCCTATTATGATTGGAGGATTCGGAAACTGATTAGTCCCATTAATAATTGGTGCCCCTGATATAGCCTTCCCACGAATAAATAATATAAGCTTCTGACTTCTACCTCCGTCCTTCCTACTTCTTCTAGCTTCCTCCATAGTTGAAGCTGGAGCAGGAACAGGCTGAACAGTTTACCCTCCTCTAGCTGGAAATCTAGCTCACGCAGGAGCCTCAGTTGACCTAACTATTTTCTCCCTACATTTAGCAGGTGTATCTTCAATTTTAGGTGCTATTAATTTTATTACTACTATTATTAATATAAAACCACCAGCCCTTTCCCAATACCAAACCCCCTTATTTGTGTGATCCGTACTAATTACAGCTGTATTATTACTACTATCTCTACCAGTTCTAGCAGCAGGAATTACAATACTATTAACAGACCGCAATCTAAATACCACTTTCTTTGACCCTGCTGGAGGAGGAGACCCCATTCTATATCAACATTTATTC"
str_dna = re.sub('[^ATCG]', '', str)
encoded_str = encode_sequence(str_dna)
lst=[encoded_str]
str_padded = tf.keras.preprocessing.sequence.pad_sequences(lst, maxlen=max_sequence_length, padding='post')
predicted_output = classifier.predict(str_padded)
predicted_probs = classifier.predict_proba(str_padded)
k=np.argmax(max(predicted_probs))
print(label_encoder.inverse_transform([k]))

['Molossops neglectus']


In [ ]:
top_n = 2
ans=[]
top_3_category = np.argsort(predicted_probs)[:, (- top_n-1) :]
for i in top_3_category[0]:
  decode=  label_encoder.inverse_transform([i])
  ans.append(decode)
top_3_probs = np.sort(predicted_probs)[:,( - top_n-1) :]

In [ ]:
# for i in ans.reverse():
#   print(i)
rev_name=list(reversed(ans))
rev_prob =list(reversed(top_3_probs[0]))
print("Predicted                      Probability")
for i in range(3):
  print(f"{rev_name[i][0]}            {rev_prob[i]} ")


Predicted                      Probability
Molossops neglectus            0.9989949496401751 
Diclidurus isabellus            0.00010502219329892401 
Cynomops planirostris            0.00010482220486313993 


#Training the SVM model on the Training set

In [ ]:
# from sklearn.svm import SVC
# svc =  SVC(kernel='linear', random_state=0, probability=True)
# svc.fit(X_train_padded,encoded_labelstrain)

### Predicting the Test set results

In [ ]:
# y_pred = svc.predict(X_test_padded)

In [ ]:
# from sklearn.metrics import confusion_matrix, accuracy_score
# print('Accuracy of SVM is: {0}%'.format(accuracy_score(encoded_labelstest, y_pred)*100))

##Extra Code

In [ ]:
# str="ACCCTATATCTCCTATTCGGTGCTTGAGCCGGGATAGTTGGGACCGCTTTGAGTCTTCTTATCCGAGCCGAATTAGGACAACCAGGAGCCCTTTTGGGAGACGACCAAATCTACAATGTAATCGTAACTGCTCATGCCTTTGTAATAATTTTTTTCATAGTAATGCCTATTATGATTGGAGGATTCGGAAACTGATTAGTCCCATTAATAATTGGTGCCCCTGATATAGCCTTCCCACGAATAAATAATATAAGCTTCTGACTTCTACCTCCGTCCTTCCTACTTCTTCTAGCTTCCTCCATAGTTGAAGCTGGAGCAGGAACAGGCTGAACAGTTTACCCTCCTCTAGCTGGAAATCTAGCTCACGCAGGAGCCTCAGTTGACCTAACTATTTTCTCCCTACATTTAGCAGGTGTATCTTCAATTTTAGGTGCTATTAATTTTATTACTACTATTATTAATATAAAACCACCAGCCCTTTCCCAATACCAAACCCCCTTATTTGTGTGATCCGTACTAATTACAGCTGTATTATTACTACTATCTCTACCAGTTCTAGCAGCAGGAATTACAATACTATTAACAGACCGCAATCTAAATACCACTTTCTTTGACCCTGCTGGAGGAGGAGACCCCATTCTATATCAACATTTATTC"
# str_dna = re.sub('[^ATCG]', '', str)
# encoded_str = encode_sequence(str_dna)
# lst=[encoded_str]
# str_padded = tf.keras.preprocessing.sequence.pad_sequences(lst, maxlen=max_sequence_length, padding='post')
# predicted_output = svc.predict(str_padded)
# predicted_probs = svc.predict_proba(str_padded)
# final_output = label_encoder.inverse_transform(predicted_output)
# print(final_output)

# top_n = 5
# ans=[]
# top_5_category = np.argsort(predicted_probs)[:, (- top_n-1) :]
# for i in top_5_category[0]:
#   decode=  label_encoder.inverse_transform([i])
#   ans.append(decode)
# top_5_probs = np.sort(predicted_probs)[:,( - top_n-1) :]

# k=np.argmax(max(predicted_probs))
# print(label_encoder.inverse_transform([k]))

In [ ]:
# indices = final_dataset[final_dataset['Sequence'] == str_dna].index
# for i in indices:
#   print(i)
#   y_final = encoded_labels[i]
#   decode=  label_encoder.inverse_transform([y_final])
#   print(y_final)
#   print(decode)
#   accuracy = accuracy_score([y_final], predicted_output)*100
#   print(f"Predicted : '{decode}' Dataset : {final_output} Accuracy : {accuracy} ")

#Pickle file

In [ ]:
# save a model
import pickle

filename = 'species.pkl'
pickle.dump(classifier, open(filename,'wb'))